#!/usr/bin/env bash
# script to run hnwProxy modules

set -e

SCRIPTDIR='/usr/local/bin'
MODULEDIR="$SCRIPTDIR/proxy_modules"

usage()
{
  echo "USAGE"
  echo "  proxy <module_name> [options]"
  echo "  proxy show"
  echo
  echo "OPTIONS"
  echo "  module_name   Run this module."
  echo "  show          List available modules."
}

if [ $# -eq 0 ]
then
  usage
else
  module=${1,,} # make lowercase
  case $module in
    "show")
      # read description files
      echo
      find $MODULEDIR -mindepth 2 -type f -name description | sort | xargs cat
      ;;
    *)
      if [ -f $MODULEDIR/$module/$module ]; then
        # run module with options
        sudo $MODULEDIR/$module/$module $2 $3 $4
      else
        usage
      fi
      ;;
    esac
fi
