---
- name: playbook (all providers)
  hosts: all
  become: true
  become_user: root
  tasks:
   - name: starting ansible run
     shell: echo $(date) >> /tmp/ansible_run

   - name: remove ufw
     apt: name=ufw state=absent purge=yes

   - name: iptables
     apt: name=iptables state=present

   - name: iptables-persistent
     apt: name=iptables-persistent state=present

   - name: iptables base rules
     script: /home/vagrant/guestfiles/firewall_base.sh

   - name: 'pptpd: install'
     apt: name=pptpd state=present

   - name: 'pptpd: enable ipv4 forwarding'
     sysctl: name=net.ipv4.ip_forward value=1 sysctl_set=yes

   - name: 'pptpd: configure'
     script: /home/vagrant/guestfiles/configure_pptpd.sh

   - name: 'pptpd: enable & restart service'
     service: name=pptpd enabled=true state=restarted
