---
- name: playbook (all providers)
  hosts: all
  sudo: true
  tasks:
   - name: starting ansible run
     shell: echo $(date) >> /tmp/ansible_run

   - name: remove ufw
     apt: name=ufw state=absent purge=yes

   - name: iptables
     apt: name=iptables state=present

   - name: iptables-persistent
     apt: name=iptables-persistent state=present

   - name: iptables base rules
     script: /home/vagrant/guestfiles/firewall_base.sh