DO:
  # DigitalOcean settings
  
  # view regions with "vagrant digitalocean-list regions $DO_TOKEN"
  # Frankfurt 1
  region: 'fra1'

  # https://github.com/devopsgroup-io/vagrant-digitalocean#configure
  token: 'your_token'
  keypath: '~/.ssh/id_rsa'
