#!/usr/bin/env bash
# install transparent proxy prerequisites

set -e

echo "Installing transparent proxy prerequisites..."

apt-get -y install python-pip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev g++

pip install mitmproxy --upgrade