#!/usr/bin/env bash
# script to redirect dns lookups

set -e

# comment that identifies this module's iptables rules
COMMENT="dns-redirect_module"

usage()
{
  echo "USAGE"
  echo "  proxy dns-redirect <dns_server>"
  echo "  proxy dns-redirect show"
  echo "  proxy dns-redirect disable"
  echo
  echo "ARGUMENTS"
  echo "  dns_server        DNS server address, IPv4 or IPv6."
  echo
  echo "OPTIONS"
  echo "  show              Show current DNS redirect if any."
  echo "  disable           Disable DNS redirection."
}

case $1 in
  "")
    usage
    ;;

  "show")
    ipv4_rule=$(iptables-save | grep $COMMENT | head -n 1)
    ipv6_rule=$(ip6tables-save | grep $COMMENT | head -n 1)

    if [[ $ipv4_rule == "" ]] && [[ $ipv6_rule == "" ]]; then
      echo "No DNS redirection in place."
    fi

    if [[ $ipv4_rule != "" ]]; then
      address=$(echo $ipv4_rule | grep -o '[^ \t]*$')
      # ^ select last space/tab delimited field from $ipv4_rule
      echo "Redirecting IPv4 DNS queries to $address"
    fi

    if [[ $ipv6_rule != "" ]]; then
      address=$(echo $ipv6_rule | grep -o '[^ \t]*$')
      echo "Redirecting IPv6 DNS queries to $address"
    fi
    ;;

  "disable")
    # remove this module's rules from iptables
    iptables-save | grep -v $COMMENT | iptables-restore
    ip6tables-save | grep -v $COMMENT | ip6tables-restore
    ;;

  *)
    if [[ $1 == *.* ]]; then
      # address cannot be IPv6 since it contains a dot
      # no need for further validation, iptables can do that

      # remove existing ipv4 rule
      iptables-save | grep -v $COMMENT | iptables-restore

      iptables -t nat -A OUTPUT -p udp --dport 53 -m comment --comment "$COMMENT" -j DNAT --to-destination $1
      iptables -t nat -A OUTPUT -p tcp --dport 53 -m comment --comment "$COMMENT" -j DNAT --to-destination $1
      iptables -t nat -A PREROUTING -p udp --dport 53 -m comment --comment "$COMMENT" -j DNAT --to-destination $1
      iptables -t nat -A PREROUTING -p tcp --dport 53 -m comment --comment "$COMMENT" -j DNAT --to-destination $1
    else
      ip6tables-save | grep -v $COMMENT | ip6tables-restore
      ip6tables -t nat -A OUTPUT -p udp --dport 53 -m comment --comment "$COMMENT" -j DNAT --to-destination $1
      ip6tables -t nat -A OUTPUT -p tcp --dport 53 -m comment --comment "$COMMENT" -j DNAT --to-destination $1
      ip6tables -t nat -A PREROUTING -p udp --dport 53 -m comment --comment "$COMMENT" -j DNAT --to-destination $1
      ip6tables -t nat -A PREROUTING -p tcp --dport 53 -m comment --comment "$COMMENT" -j DNAT --to-destination $1

    fi
    ;;
esac
