#!/usr/bin/env bash
# script to break mtu

INTERFACE=$(cat /var/external_interface)
CUR_MTU=$(ip link show $INTERFACE | sed -n '1p' | cut -d ' ' -f 5)

if [ $# -eq 0 ]
then
  echo
  echo "$INTERFACE current MTU: $CUR_MTU"
  echo
  echo "Usage: proxy mtu [value]"
  echo
else
  ip link set $INTERFACE mtu $1
fi
